//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Youtube_Audio_Downloader {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Youtube_Audio_Downloader.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error al descargar:.
        /// </summary>
        public static string error_download_text {
            get {
                return ResourceManager.GetString("error_download_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error al descargar.
        /// </summary>
        public static string error_download_title {
            get {
                return ResourceManager.GetString("error_download_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Descargar Video.
        /// </summary>
        public static string mainwnd_downloadbtn_text {
            get {
                return ResourceManager.GetString("mainwnd_downloadbtn_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Descargando %(file)s - ETA: %(time)s.
        /// </summary>
        public static string mainwnd_downloadprogress_text {
            get {
                return ResourceManager.GetString("mainwnd_downloadprogress_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Buscando playlist, espere por favor....
        /// </summary>
        public static string mainwnd_searchingplaylist_text {
            get {
                return ResourceManager.GetString("mainwnd_searchingplaylist_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Buscando video, espere por favor....
        /// </summary>
        public static string mainwnd_searchingvideo_text {
            get {
                return ResourceManager.GetString("mainwnd_searchingvideo_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Inserte una url de un video de youtube.
        /// </summary>
        public static string mainwnd_textbox_placeholder {
            get {
                return ResourceManager.GetString("mainwnd_textbox_placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Descargar Musicas de Youtube.
        /// </summary>
        public static string mainwnd_title {
            get {
                return ResourceManager.GetString("mainwnd_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Playlist.
        /// </summary>
        public static string playlist_default_name {
            get {
                return ResourceManager.GetString("playlist_default_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Descarga de la playlist completada.
        /// </summary>
        public static string playlist_succesfuldownload_text {
            get {
                return ResourceManager.GetString("playlist_succesfuldownload_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Playlist descargada.
        /// </summary>
        public static string playlist_succesfuldownload_title {
            get {
                return ResourceManager.GetString("playlist_succesfuldownload_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Donde guardo la playlist?.
        /// </summary>
        public static string playlist_wheresave_title {
            get {
                return ResourceManager.GetString("playlist_wheresave_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a --ffmpeg-location binaries/ffmpeg.exe -x --audio-format mp3 -o &quot;%(folder)s\%(title)s.%(ext)s&quot; %(url)s.
        /// </summary>
        public static string playlistdownload_ytdlp_args {
            get {
                return ResourceManager.GetString("playlistdownload_ytdlp_args", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error al borrar la carpeta ¿Faltan permisos?.
        /// </summary>
        public static string playlisterror_cannotdeletefolder_text {
            get {
                return ResourceManager.GetString("playlisterror_cannotdeletefolder_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error al sobreescribir carpeta.
        /// </summary>
        public static string playlisterror_cannotdeletefolder_title {
            get {
                return ResourceManager.GetString("playlisterror_cannotdeletefolder_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se ha podido guardar la playlist en la ubicación seleccionada &quot;%(folder)s&quot;.
        /// </summary>
        public static string playlisterror_cannotsave {
            get {
                return ResourceManager.GetString("playlisterror_cannotsave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error obteniendo la información de la playlist.
        /// </summary>
        public static string playlisterror_getplaylist_title {
            get {
                return ResourceManager.GetString("playlisterror_getplaylist_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Esta playlist contiene una url que no es valida.
        /// </summary>
        public static string playlisterror_invalid {
            get {
                return ResourceManager.GetString("playlisterror_invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Esta playlist no contiene videos.
        /// </summary>
        public static string playlisterror_novideos {
            get {
                return ResourceManager.GetString("playlisterror_novideos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a --flat-playlist --print &quot;%(playlist)s - %(title)s&quot; --no-download %(url)s.
        /// </summary>
        public static string playlistinfo_ytdlp_args {
            get {
                return ResourceManager.GetString("playlistinfo_ytdlp_args", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La carpeta %(folder)s ya existe. Se borrara toda la información que contenga. ¿Desea Continuar?.
        /// </summary>
        public static string playlistwarning_folderalreadyexist_text {
            get {
                return ResourceManager.GetString("playlistwarning_folderalreadyexist_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Carpeta de playlist ya existe.
        /// </summary>
        public static string playlistwarning_folderalreadyexist_title {
            get {
                return ResourceManager.GetString("playlistwarning_folderalreadyexist_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Preparando descarga. Espere un momento....
        /// </summary>
        public static string preparingdownload_text {
            get {
                return ResourceManager.GetString("preparingdownload_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a youtube_audio_downloader.
        /// </summary>
        public static string prog_tempfolder_name {
            get {
                return ResourceManager.GetString("prog_tempfolder_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Guardando archivo. Espere un momento....
        /// </summary>
        public static string savingdownload_text {
            get {
                return ResourceManager.GetString("savingdownload_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a -U.
        /// </summary>
        public static string update_ytdlp_args {
            get {
                return ResourceManager.GetString("update_ytdlp_args", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Buscando y descargando actualizaciones....
        /// </summary>
        public static string updaterwnd_text {
            get {
                return ResourceManager.GetString("updaterwnd_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Updater.
        /// </summary>
        public static string updaterwnd_title {
            get {
                return ResourceManager.GetString("updaterwnd_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Video.
        /// </summary>
        public static string video_default_name {
            get {
                return ResourceManager.GetString("video_default_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Audio Descargado Satisfactoriamente.
        /// </summary>
        public static string video_succesfuldownload_text {
            get {
                return ResourceManager.GetString("video_succesfuldownload_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Descarga completada.
        /// </summary>
        public static string video_succesfuldownload_title {
            get {
                return ResourceManager.GetString("video_succesfuldownload_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Archivo MP3 (*.mp3)|*.mp3.
        /// </summary>
        public static string video_wheresave_filter {
            get {
                return ResourceManager.GetString("video_wheresave_filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Donde guardo la musica?.
        /// </summary>
        public static string video_wheresave_title {
            get {
                return ResourceManager.GetString("video_wheresave_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a --ffmpeg-location binaries/ffmpeg.exe -x --audio-format mp3 -o &quot;%(downloadFolder)s\%(fileName)s&quot; %(url)s.
        /// </summary>
        public static string videodownload_ytdlp_args {
            get {
                return ResourceManager.GetString("videodownload_ytdlp_args", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se ha podido guardar el archivo en la ubicación seleccionada &quot;%(folder)s&quot;.
        /// </summary>
        public static string videoerror_cannotsave {
            get {
                return ResourceManager.GetString("videoerror_cannotsave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error obteniendo información del video.
        /// </summary>
        public static string videoerror_getvideo_title {
            get {
                return ResourceManager.GetString("videoerror_getvideo_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El video contiene una url invalida.
        /// </summary>
        public static string videoerror_invalid {
            get {
                return ResourceManager.GetString("videoerror_invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a --print &quot;%(title)s&quot; --no-download %(url)s.
        /// </summary>
        public static string videoinfo_ytdlp_args {
            get {
                return ResourceManager.GetString("videoinfo_ytdlp_args", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a binaries/yt-dlp.exe.
        /// </summary>
        public static string ytdlp_path {
            get {
                return ResourceManager.GetString("ytdlp_path", resourceCulture);
            }
        }
    }
}
